language: julia
os:
  - linux
  - osx
  - windows
julia:
  - '1.0'
  - '1.3'
  - '1'
  - 'nightly'
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
